import { AcademicDocument, PDFPageViewData } from '../types';
import { mockDocuments, mockPage421Content, mockPage512Content } from '../data/mockData';

/**
 * Document Service Interface
 * Pre-configured for future connection to FastAPI / Python backend, S3/GCS bucket uploads,
 * and vector-indexing pipelines (e.g. Pinecone, ChromaDB, PGVector).
 */
export const DocumentService = {
  /**
   * Fetch all user documents
   */
  async getDocuments(): Promise<AcademicDocument[]> {
    // Simulated network delay
    await new Promise((resolve) => setTimeout(resolve, 150));
    return [...mockDocuments];
  },

  /**
   * Fetch single document by ID
   */
  async getDocumentById(id: string): Promise<AcademicDocument | undefined> {
    await new Promise((resolve) => setTimeout(resolve, 100));
    return mockDocuments.find((doc) => doc.id === id);
  },

  /**
   * Fetch rendered PDF page content and metadata
   */
  async getPageContent(documentId: string, pageNumber: number): Promise<PDFPageViewData> {
    await new Promise((resolve) => setTimeout(resolve, 120));

    if (pageNumber >= 500 && pageNumber <= 550) {
      return {
        ...mockPage512Content,
        pageNumber,
      };
    }

    // Default to page 421 deadlocks content with page number adjustments
    return {
      ...mockPage421Content,
      pageNumber,
    };
  },

  /**
   * Search within a large document (RAG retrieval placeholder)
   */
  async searchDocumentText(documentId: string, query: string): Promise<{ page: number; excerpt: string; section: string }[]> {
    await new Promise((resolve) => setTimeout(resolve, 200));
    const q = query.toLowerCase();

    const results = [
      {
        page: 421,
        section: 'Section 7.4 Deadlock Prevention',
        excerpt: 'By ensuring that at least one of these conditions cannot hold, we can systematically prevent the occurrence of a deadlock...',
      },
      {
        page: 423,
        section: 'Section 7.4.4 Circular-Wait Condition Denial',
        excerpt: 'We can enforce that each process can request resources only in an increasing order of enumeration...',
      },
      {
        page: 435,
        section: 'Section 7.5 Deadlock Avoidance Algorithms',
        excerpt: 'A deadlock-avoidance algorithm dynamically examines the resource-allocation state to ensure a circular-wait condition can never exist...',
      },
      {
        page: 512,
        section: 'Section 8.3 Paging Hardware and Translation Lookaside Buffer',
        excerpt: 'The TLB contains only a few of the page-table entries. When a logical address is generated by the CPU...',
      },
    ];

    if (!q) return results;
    return results.filter((r) => r.excerpt.toLowerCase().includes(q) || r.section.toLowerCase().includes(q));
  },

  /**
   * Simulate uploading an academic PDF
   */
  async uploadDocument(
    file: File,
    onProgress?: (progress: number, stepName: string) => void
  ): Promise<AcademicDocument> {
    const steps = [
      { pct: 15, msg: 'File uploaded & sha256 checksum verified' },
      { pct: 35, msg: 'PDF header parsed & font glyphs mapped' },
      { pct: 60, msg: 'Text extracted & academic formulas detected' },
      { pct: 85, msg: 'Sections & Table of Contents identified' },
      { pct: 95, msg: 'Generating dense vector embeddings' },
      { pct: 100, msg: 'Document indexed & ready for Q&A' },
    ];

    for (const step of steps) {
      await new Promise((resolve) => setTimeout(resolve, 400));
      if (onProgress) {
        onProgress(step.pct, step.msg);
      }
    }

    const newDoc: AcademicDocument = {
      id: `doc-${Date.now()}`,
      title: file.name.replace(/\.[^/.]+$/, ''),
      subject: 'Computer Science',
      totalPages: 486,
      status: 'processed',
      processingProgress: 100,
      lastStudied: 'Just now',
      uploadedAt: 'Today',
      fileSize: `${(file.size / (1024 * 1024)).toFixed(1)} MB`,
      color: 'from-blue-600 to-indigo-700',
      description: 'Recently uploaded academic syllabus notes, parsed with deep structural indexing.',
      chapters: [
        { id: 'ch-new-1', number: 1, title: 'Chapter 1: Foundational Principles', pageStart: 1, pageEnd: 95 },
        { id: 'ch-new-2', number: 2, title: 'Chapter 2: Core Architectures & Proofs', pageStart: 96, pageEnd: 240 },
        { id: 'ch-new-3', number: 3, title: 'Chapter 3: Advanced Applications', pageStart: 241, pageEnd: 486 },
      ],
    };

    return newDoc;
  },

  /**
   * Delete document
   */
  async deleteDocument(id: string): Promise<boolean> {
    await new Promise((resolve) => setTimeout(resolve, 150));
    return true;
  },
};
